### ISSUE TITLE
updates based on feedback from jread

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/usgs-r-website#117]
- [x] can you have past trainings in one color and upcoming (planned or tentative trainings) in another color? That way people can see if there is an upcoming one by them that they could latch on to. 
- [x] I think the link to the training curriculum is hidden a bit. Would it be worth the materials having their own section in that page? Completed by @ldecicco-USGS already (see what's going on with https://github.com/USGS-R/intro-curriculum)
- [x] Can the product reviews be a bit smaller? Maybe do one fewer row?
- [x] any reason no to borrow some of the content from the datasci webpage for training? I like the workflow featured there and maybe one of the pictures would be good to add

**Comment by lindsaycarr** [comment]
The first two tasks seem like they would be @mwernimont things to do. The last one I think I could do.

**Comment by mwernimont** [comment]
@jread-usgs Lindsay made the review section one less row and hould be on Dev? if we have one for this website. Also you think over the button showing up for the open R events being enough?
