### ISSUE TITLE
nav dropdown does not show up sometimes

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/usgs-r-website#132]
The training dropdown does not appear when you are on http://owi.usgs.gov/R/ but shows up when there URL ends with `.html` (so after clicking Home, About, Resources, Training, GRAN, or Contact

**Comment by lindsaycarr** [comment]
@mwernimont can you look into this if/when you have time? Thanks.

**Comment by lindsaycarr** [comment]
wait...now it appears to be working

**Comment by lawinslow** [comment]
Beware of both the cloudfront *and* your local cache.
