### ISSUE TITLE
add favico

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/usgs-r-website#14]

**Comment by jread-usgs** [comment]
@mwernimont can you add something like this? 
![image](https://cloud.githubusercontent.com/assets/2349007/6415004/65aac42a-be61-11e4-86b9-cc3140367933.png)

**Comment by mwernimont** [comment]
@jread-usgs Sure can

**Comment by jread-usgs** [comment]
@mwernimont quick change to this: can you make the white part transparent instead? 
![image](https://cloud.githubusercontent.com/assets/2349007/6415184/0af10132-be63-11e4-85f0-48930188e2e4.png)

**Comment by jread-usgs** [comment]
looks great now

**Comment by mwernimont** [comment]
Always does

**Comment by jread-usgs** [comment]
every day
