### ISSUE TITLE
simple Google Analytics

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/usgs-r-website#144]
Interested to see how much traffic and where people go on our site. I've got no idea how to add anything, but could give this a go if someone \*ahem* @jiwalker-usgs \*ahem* helped me get started.

**Comment by ldecicco-USGS** [comment]
We do have it in there....although it looks like it's the Vizlab id:

![image](https://cloud.githubusercontent.com/assets/1105215/20542011/48d1c4ae-b0c5-11e6-84dc-4d1fb6ce7924.png)


![image](https://cloud.githubusercontent.com/assets/1105215/20542035/6982c2fc-b0c5-11e6-980c-b068876f291c.png)

![image](https://cloud.githubusercontent.com/assets/1105215/20542051/7be057de-b0c5-11e6-8873-58afe347b387.png)

**Comment by ldecicco-USGS** [comment]
If you want to change the ID...it's actually in the Jenkin's job.

**Comment by ldecicco-USGS** [comment]
Oh....and that was just for the training stuff. The basic .html files (index, gran, etc), they all have the "USGS-R" google analytic id:

So, dating back all the way to March 2015:

![image](https://cloud.githubusercontent.com/assets/1105215/20542255/745c11f0-b0c6-11e6-9f3c-27e8136f37b4.png)

**Comment by lindsaycarr** [comment]
Hmm OK. Did not know this - thanks @ldecicco-USGS!

**Comment by ldecicco-USGS** [comment]
well, we might want to adjust the GA id....to be more consistent with USGS-R. But, the info is there.

**Comment by lindsaycarr** [comment]
Shall I reopen so we can chat about this in the future?
