### ISSUE TITLE
update Coursera link since it's not free

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/usgs-r-website#149]
> It looks like the pricing for that course has changed- it used to be offered for free (and a paid course w/ add'l options for students), but now it is not. We will update our OWI-R site to reflect this, and will also work to make some recommendations on other free training options

This is linked in Resources >> Getting Started

You can still audit the course. Maybe include that or find other resources. List suggestions in this issue.

**Comment by wdwatkins** [comment]
![screen shot 2017-01-23 at 9 39 47 am](https://cloud.githubusercontent.com/assets/13987349/22212080/f1dccee4-e154-11e6-9def-504b4c67bdcd.png)

Maybe specify the location of the audit link?

This could be another course worth posting also: https://www.coursera.org/learn/r-packages

**Comment by lindsaycarr** [comment]
https://www.tutorialspoint.com/r/index.htm

**Comment by lindsaycarr** [comment]
Follow along with either of these tutorials:

swirl (http://swirlstats.com/) or Code School (http://tryr.codeschool.com/levels/1/challenges/1)

**Comment by lindsaycarr** [comment]
@wdwatkins where exactly is that audit link? Do you have to login/signup first?

**Comment by wdwatkins** [comment]
It's in the window that comes up when you click "Enroll".  You do need to make an account first I think
