### ISSUE TITLE
Add google analytics?

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/usgs-r-website#45]

**Comment by jread-usgs** [comment]
@lawinslow were you going to do this one too while addressing andrew's comments?

**Comment by lawinslow** [comment]
yup

**Comment by lawinslow** [comment]
Will do this Monday when I can get a new analytics ID setup with the CIDA account.

**Comment by jread-usgs** [comment]
Any luck on this? we definitely want it active when the announcement is made.

**Comment by lawinslow** [comment]
boom
