### ISSUE TITLE
Add "under development" tag to two of the featured packages

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/usgs-r-website#68]
@mwernimont could you do this?
![image](https://cloud.githubusercontent.com/assets/2349007/6416383/5b13a4dc-be6b-11e4-92c7-3084a971d9b9.png)

**Comment by jread-usgs** [comment]
Where the color of that tag matches the "R Developers" color?

**Comment by mwernimont** [comment]
@jread-usgs I have a few other things on my plate, but would like to try it when I have time

**Comment by jread-usgs** [comment]
Sounds good. Thanks

**Comment by jread-usgs** [comment]
@mwernimont any time for this today?
