### ISSUE TITLE
link at bottom of page should link back to owi.usgs.gov/R, not cida homepage

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/usgs-r-website#80]
yes, circular, but requested by the boss.

**Comment by jread-usgs** [comment]
whoops. our bad

**Comment by ldecicco-USGS** [comment]
I think there might be another bad link in the footer:
http://www.doioig.gov/

**Comment by ldecicco-USGS** [comment]
Well, maybe that's right....
