### ISSUE TITLE
owi.usgs.gov/R looks AWFUL on IE

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/usgs-r-website#82]

**Comment by ldecicco-USGS** [comment]
@mwernimont  can you look into this?

**Comment by ldecicco-USGS** [comment]
What's interesting is that the raw files, opened in IE, look just fine. rawgit looks fine in IE too:

https://rawgit.com/USGS-R/usgs-r-website/master/index.html

**Comment by ldecicco-USGS** [comment]
@jiwalker-usgs has a theory

**Comment by lawinslow** [comment]
What is it? My theory is case sensitivity on Amazon S3

**Comment by ldecicco-USGS** [comment]
Yup, if you turn off compatibility mode, and get out of the USGS firewall, it looks fine again

**Comment by jiwalker-usgs** [comment]
http://stackoverflow.com/questions/4275356/ie-compatibility-mode-x-ua-compatible-tag-edge-question give some conflicting answers, but if we throw in the meta tag it should work within the DOI network.

**Comment by ldecicco-USGS** [comment]
Actually, I don't think you need to be out of the firewall, just not in compatibility mode.

**Comment by jiwalker-usgs** [comment]
yeah, you can force pages to not use compatibility mode with <meta http-equiv="X-UA-Compatible" content="IE=Edge" /> I think.

**Comment by lawinslow** [comment]
This then? 
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

**Comment by ldecicco-USGS** [comment]
I'm giving it a shot, one sec

**Comment by ldecicco-USGS** [comment]
I think it's good. Can someone else verify just in case I permanently set my browser to ignore the compatibility mode? I'm pretty sure I un-disabled that, but it's worth a check before closing the issue.

**Comment by jiwalker-usgs** [comment]
looks good to me

**Comment by ldecicco-USGS** [comment]
huzzuh
