### ISSUE TITLE
Make gitHub intro page

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/usgs-r-website#9]
We need a document we can send people to describe how to get on USGS-R, the preferred workflow (Pull Requests). Who to contact (me? should we set up an email list? GRAN@usgs.gov or something) to get on teams, how to make a new repository (still use gitpilot jira?).

**Comment by lawinslow** [comment]
Two thoughts on this. One, setup an email list. Or two, just have a specific person on point. Email lists always seem to eventually bit rot. I'm happy to be GRAN point of contact if needed.

**Comment by jread-usgs** [comment]
luke = ripley

**Comment by lawinslow** [comment]
please only send your comments in the ASCII format as I prefer to read my email from a windows 95 DOS command prompt on dial-up

**Comment by ldecicco-USGS** [comment]
I've had great experiences with small email lists. What I meant was we put GRAN@usgs.gov on the help page and only you guys get an email that someone wants to set up a new repository on USGS-R for example. But, I'm happy to let @lawinslow be the contact.

NOT, everyone who wants to be a part of USGS-R or GRAN is on this list, just the Owners or something like that.

GRAN is actually not really what I was getting at. Using gitHub and the USGS-R group (and then by extension GRAN) is what I feel like we need.

**Comment by lawinslow** [comment]
How about "USGS-R Maintainers"? As per a few interesting write-ups I've seen, maybe we could even just use a github repo with issues as the place for discussion. Make all maintainers subscribe to it.

**Comment by ldecicco-USGS** [comment]
Sounds like a plan.
